name: OpenWrt-CI

on:
  push:
    branches:
      - main
    paths:
      - 'script.sh'
      - 'config.sh'
  schedule:
    - cron: 0 8 * * 0
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  SCRIPT_SH: script.sh
  CONFIG_SH: config.sh
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai
  KERNEL_VERSION: 6.1.79

jobs:
  build_openwrt:
    name: Build OpenWrt and release
    runs-on: ubuntu-22.04

    steps:

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true

    - name: Checkout
      uses: actions/checkout@v3.1.0
      with:
        ref: main

    - name: Disk space
      run: |
           echo "Free space:"
           df -h

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-mark hold grub-efi-amd64-signed
        sudo -E apt-get -qq update --fix-missing
        sudo -E apt-get -qq full-upgrade
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo timedatectl set-timezone "$TZ"

    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        useVersionInfo=$(git show -s --date=short --format="date: %cd<br/>commit: %s<br/>commit hash: %H")
        echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "tag_name=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Update feeds
      run: |
        [ -e files ] && mv files openwrt/files
        chmod +x $SCRIPT_SH
        cd openwrt
        echo "src-git helloworld https://github.com/fw876/helloworld.git" >> "feeds.conf.default"
        ./scripts/feeds update -a
        cat feeds/packages/utils/xfsprogs/Makefile
        sed -i 's/TARGET_CFLAGS += -DHAVE_MAP_SYNC/TARGET_CFLAGS += -DHAVE_MAP_SYNC -D_LARGEFILE64_SOURCE/' feeds/packages/utils/xfsprogs/Makefile
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cd ..
        sh -x $SCRIPT_SH
        cd openwrt
        grep '192.168' package/base-files/files/bin/config_generate

    - name: Generate configuration file
      run: |
        cd openwrt
        make defconfig

    - name: Load custom configuration
      run: |
        chmod +x $CONFIG_SH
        ./$CONFIG_SH

    - name: Download package
      run: |
        cd openwrt
        make download -j8

    - name: Compile the firmware
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "======================="
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
        du -h --max-depth=1 ./build_dir
        du -h --max-depth=1 ./bin

    - name: Prepare artifact
      run: |
        cd openwrt
        mkdir -p ./artifact/package
        mkdir -p ./artifact/buildinfo
        rm -rf $(find ./bin/targets/ -type d -name "packages")
        cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
        cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
        cp -rf .config ./artifact/buildinfo/build.config

    - name: Upload buildinfo
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_buildinfo
        path: ./openwrt/artifact/buildinfo/

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_package
        path: ./openwrt/artifact/package/

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_firmware
        path: ./openwrt/bin/targets/
